### ISSUE TITLE
Error when trying to use getTimetable

### ISSUE THREAD

**Issue by its-avery** [tuesd4y/node-webuntis#10]
The code I used:
TimeTableEntity = e.TimeTableEntity;
        w.getTimetable(new TimeTableEntity(1, 5)).then(data => console.log(data));

The error I got:
(node:18444) UnhandledPromiseRejectionWarning: Error: [object Object]
    at C:\Users\paede\OneDrive\Desktop\Schule\sommersemprojekt\node_modules\untis-api\webuntis.js:183:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

How can I resolve this error

**Comment by its-avery** [comment]
is solved

**Comment by tuesd4y** [comment]
I'm glad to hear that! As you might have noticed, I'm not actively contributing to this project anymore, but if there's any features you need feel free to submit PRs!

**Comment by its-avery** [comment]
It was just a problem that I did myself. To solve it i just  started the server with --unhandled-rejections=none. So it doesnt stop with it. Now my only question is what the things that i get mean.

**Comment by its-avery** [comment]
If you need someone who answers the questions and extends the wiki, I could help you.

**Comment by its-avery** [comment]
the problem is still there

**Comment by its-avery** [comment]
function getTimetable(timeTableEntity, dateInWeek) {
    return new Promise((resolve, reject) => {
        if (isUndefined(timeTableEntity)) {
            throw Error("please pass a timeTableEntity");
        }

        if (isUndefined(dateInWeek) || !isDate(dateInWeek)) {
            dateInWeek = moment();
        }

        let startDate = dateInWeek.subtract(dateInWeek.day(), 'days').add(1, 'days');

        let endDate = startDate.clone().add(5, 'days');

        connectPromise.then(rpc.rpc("getTimetable", {
            type: timeTableEntity.type,
            id: timeTableEntity.id,
            startDate: parseInt(startDate.format(DATE_FORMAT)),
            endDate: parseInt(endDate.format(DATE_FORMAT)),
        }, data => {
                    try{
                    if(data.error){
                        throw Error(data.error);
                    }
                }
                catch(error){
                    console.log(error);
            }
                resolve(data.result);
        }))
    });
}
this solves one error. Now it says that i dont have the permission to do it
